lib/mango_web/router.ex
defmodule MangoWeb.Router do
  use MangoWeb, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", MangoWeb do
    pipe_through :browser # Use the default browser stack

    get "/", PageController, :index
    get "/categories/:name", CategoryController, :show

    get "/register", RegisterationController, :new
    post "/register", RegisterationController, :create
  end

  # Other scopes may use custom stacks.
  # scope "/api", MangoWeb do
  #   pipe_through :api
  # end
end

lib/mango/application.ex
defmodule Mango.Application do
  use Application

  # See https://hexdocs.pm/elixir/Application.html
  # for more information on OTP Applications
  def start(_type, _args) do
    import Supervisor.Spec

    # Define workers and child supervisors to be supervised
    children = [
      # Start the Ecto repository
      supervisor(Mango.Repo, []),
      # Start the endpoint when the application starts
      supervisor(MangoWeb.Endpoint, []),
      # Start your own worker by calling: Mango.Worker.start_link(arg1, arg2, arg3)
      # worker(Mango.Worker, [arg1, arg2, arg3]),
    ]

    # See https://hexdocs.pm/elixir/Supervisor.html
    # for other strategies and supported options
    opts = [strategy: :one_for_one, name: Mango.Supervisor]
    Supervisor.start_link(children, opts)
  end

  # Tell Phoenix to update the endpoint configuration
  # whenever the application is updated.
  def config_change(changed, _new, removed) do
    MangoWeb.Endpoint.config_change(changed, removed)
    :ok
  end
end

lib/mango/catalog/catalog.ex
defmodule Mango.Catalog do
  alias Mango.Catalog.Product
  alias Mango.Repo

  def list_products do
    Product
    |> Repo.all
  end

  def list_seasonal_products do
    list_products()
    |> Enum.filter(fn(product) -> product.is_seasonal == true end)
  end

  def get_category_products(category) do
    list_products()
    |> Enum.filter(fn(product) -> product.category == category end)
  end
end

lib/mango/catalog/product.ex
defmodule Mango.Catalog.Product do
  use Ecto.Schema

  schema "products" do
    field :image, :string
    field :is_seasonal, :boolean, default: false
    field :name, :string
    field :price, :decimal
    field :sku, :string
    field :category, :string
    field :pack_size, :string

    timestamps()
  end
end

lib/mango/crm/crm.ex
defmodule Mango.CRM do
  alias Mango.CRM.Customer
  alias Mango.Repo

  def build_customer(attrs \\ %{}) do
    %Customer{}
    |> Customer.changeset(attrs)
  end

  def create_customer(attrs) do
    attrs
    |> build_customer
    |> Repo.insert
  end
end

lib/mango/crm/customer.ex
defmodule Mango.CRM.Customer do
  use Ecto.Schema
  import Ecto.Changeset
  alias Mango.CRM.Customer
  import Comeonin.Bcrypt, only: [hashpwsalt: 1]

  schema "customers" do
    field :email, :string
    field :name, :string
    field :password, :string, virtual: true
    field :password_hash, :string
    field :phone, :string
    field :residence_area, :string

    timestamps()
  end

  @doc false
  def changeset(%Customer{} = customer, attrs) do
    customer
    |> cast(attrs, [:name, :email, :phone, :residence_area, :password])
    |> validate_required([:name, :email, :phone, :residence_area, :password])
    |> validate_format(:email, ~r/@/, message: "is invalid")
    |> validate_length(:password, min: 6, max: 100)
    |> unique_constraint(:email)
    |> put_hashed_password()
  end

  defp put_hashed_password(changeset) do
    case changeset.valid? do
      true->
        changes = changeset.changes
        put_change(changeset, :password, hashpwsalt(changes.password))
      _ ->
        changeset
      end
  end
end

lib/mango/repo.ex
defmodule Mango.Repo do
  use Ecto.Repo, otp_app: :mango

  @doc """
  Dynamically loads the repository url from the
  DATABASE_URL environment variable.
  """
  def init(_, opts) do
    {:ok, Keyword.put(opts, :url, System.get_env("DATABASE_URL"))}
  end
end

lib/mango_web/controllers/category_controller.ex
defmodule MangoWeb.CategoryController do
  use MangoWeb, :controller
  alias Mango.Catalog

  def show(conn, %{"name" => name}) do
    products = Catalog.get_category_products(name)
    conn
    |> assign(:products, products)
    |> assign(:name, name)
    |> render("show.html")
  end
end

lib/mango_web/controllers/page_controller.ex
defmodule MangoWeb.PageController do
  use MangoWeb, :controller
  alias Mango.Catalog

  def index(conn, _params) do
    seasonal_products = Catalog.list_seasonal_products()
    new_conn = assign(conn, :seasonal_products, seasonal_products)
    render new_conn, "index.html"
  end
end

lib/mango_web/controllers/registeration_controller.ex
defmodule MangoWeb.RegisterationController do
  use MangoWeb, :controller
  alias Mango.CRM

  def new(conn, _) do
    changeset = CRM.build_customer
    render(conn, "new.html", changeset: changeset)
  end

  def create(conn, %{"registeration" => registeration_data} = params) do
  end
end

lib/mango_web/views/category_view.ex
defmodule MangoWeb.CategoryView do
  use MangoWeb, :view

  def title_case(name) do
    name
    |> String.downcase
    |> String.capitalize
  end
end

lib/mango_web/views/error_view.ex
defmodule MangoWeb.ErrorView do
  use MangoWeb, :view

  def render("404.html", _assigns) do
    "Page not found"
  end

  def render("500.html", _assigns) do
    "Internal server error"
  end

  # In case no render clause matches or no
  # template is found, let's render it as 500
  def template_not_found(_template, assigns) do
    render "500.html", assigns
  end
end

lib/mango_web/views/layout_view.ex
defmodule MangoWeb.LayoutView do
  use MangoWeb, :view
end

lib/mango_web/views/page_view.ex
defmodule MangoWeb.PageView do
  use MangoWeb, :view
end

lib/mango_web/views/product_view.ex
defmodule MangoWeb.ProductView do
  use MangoWeb, :view
end

lib/mango_web/views/registeration_view.ex
defmodule MangoWeb.RegisterationView do
  use MangoWeb, :view
end

lib/mango_web/templates/category/show.html.eex
<h1 class="page-title"><%= title_case @name %></h1>
<div>
  <%= for product <- @products do %>
    <div class="col-md-4">
      <%= render MangoWeb.ProductView, "product_card.html", product: product %>
    </div>
  <% end %>
</div>

lib/mango_web/templates/layout/app.html.eex
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Hello Mango!</title>
    <link rel="stylesheet" href="<%= static_path(@conn, "/css/app.css") %>">
  </head>

  <body>
    <%= render "app_nav.html", conn: @conn%>
    <div class="container">
      <p class="alert alert-info" role="alert"><%= get_flash(@conn, :info) %></p>
      <p class="alert alert-danger" role="alert"><%= get_flash(@conn, :error) %></p>

      <main role="main">
        <%= render @view_module, @view_template, assigns %>
      </main>

    </div> <!-- /container -->
    <script src="<%= static_path(@conn, "/js/app.js") %>"></script>
  </body>
</html>

lib/mango_web/templates/layout/app_nav.html.eex
<nav class="navbar navbar-default navbar-fixed-top">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" datatoggle="collapse" data-target="#primary-nav">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="/">
        <img src="/images/logo.png"/> Mango
      </a>
    </div>
    <div class="collapse navbar-collapse" id="primary-nav">
      <ul class="nav navbar-nav">
        <li><%= link "Fruits", to: category_path(@conn, :show, "fruits") %></li>
        <li><%= link "Vegetables", to: category_path(@conn, :show, "vegetables") %></li>
      </ul>
    </div>
  </div>
</nav>

lib/mango_web/templates/page/index.html.eex
<h1 class="page-title">Seasonal Products</h1>
<div>
  <%= for product <- @seasonal_products do %>
    <div class="col-md-4">
      <%= render MangoWeb.ProductView, "product_card.html", product: product %>
    </div>
  <% end %>
</div>

lib/mango_web/templates/product/product_card.html.eex
<div class="product thumbnail">
  <div class="caption">
    <span class="text-muted pull-right"><%= @product.pack_size %></span>
    <h2>
      <div class="product-name"><%= @product.name %></div>
      <span class="pull-right">
        <small class="product-price">INR <%= @product.price %></small>
      </span>
    </h2>
  </div>
  <img src="<%= @product.image %>" />
</div>

lib/mango_web/templates/registeration/new.html.eex
<h1>Register Account</h1>
<%= form_for @changeset, registeration_path(@conn, :create), [as: :registeration, id: "registeration-form"], fn f -> %>
  <div class="form-group">
    <%= label f, :name, class: "control-label" %>
    <%= text_input f, :name, class: "form-control" %>
    <%= error_tag f, :name %>
  </div>

  <div class="form-group">
    <%= label f, :email, class: "control-label" %>
    <%= text_input f, :email, class: "form-control" %>
    <%= error_tag f, :email %>
  </div>

  <div class="form-group">
    <%= label f, :phone, class: "control-label" %>
    <%= text_input f, :phone, class: "form-control" %>
    <%= error_tag f, :phone %>
  </div>

  <div class="form-group">
    <%= label f, :residence_area, "Area of Residence", class: "control-label" %>
    <%= text_input f, :residence_area, class: "form-control" %>
    <%= error_tag f, :residence_area %>
  </div>

  <div class="form-group">
    <%= label f, :password, class: "control-label" %>
    <%= text_input f, :password, placeholder: "Password", class: "form-control" %>
    <%= error_tag f, :password %>
  </div>

  <%= submit "Register", class: "btn btn-primary" %>
<% end %>